[package]
name = "client_api"
version = "0.1.0"
edition = "2021"

[lib]
name = "client_api"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
leptos = { version = "0.6.14", features = ["csr", "nightly"] }
