[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
mongodb = { version = "2.8.1", features = ["tokio-runtime"] }
serde = "1.0.197"
tokio = { version = "1.36.0", features = ["full"] }
toml = "0.8.10"
