[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.0"
chrono = { version = "0.4.34", features = ["serde"] }
erased-serde = "0.4.4"
futures = "0.3.30"
mongodb = { version = "2.8.1", features = ["tokio-runtime"] }
reqwest = "0.12.1"
rocket = { version = "0.5.0", features = ["json"] }
serde = "1.0.197"
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["full"] }
toml = "0.8.10"
types = {path = "../types", features = ["server"]}
url = { version = "2.5.0", features = ["serde"] }
